[package]
name = "day8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent = { git = "https://github.com/rossmacarthur/advent", tag = "0.1.0" }
indexmap = "2.1.0"
